import { TypeLanguageCode } from "./type";

// Google Cloud API の入力に必要なデータを管理
export const languageCodeList: Array<TypeLanguageCode> = [
  {
    code: "en-us",
    shortCode: "en",
    name: "英語（アメリカ）",
    placeholder: "Speak your language",
    speak: { code: "en-US", speaker: "en-US-Neural2-J" },
  },
  {
    code: "en-gb",
    shortCode: "en",
    name: "英語（イギリス）",
    speak: { code: "en-GB", speaker: "en-GB-Neural2-C" },
  },
  {
    code: "cmn-hant-tw",
    shortCode: "zh-tw",
    name: "繁体字（台湾）",
    placeholder: "說你的語言",
    speak: { code: "cmn-TW", speaker: "cmn-TW-Wavenet-A" },
  },
  {
    code: "cmn-hans-cn",
    shortCode: "zh-cn",
    name: "簡体字（中国）",
    placeholder: "说你的语言",
    speak: { code: "cmn-CN", speaker: "cmn-CN-Wavenet-C" },
  },
  {
    code: "fil-ph",
    shortCode: "fil",
    name: "タガログ語（フィリピン）",
    placeholder: "magsalita ng iyong wika",
    speak: { code: "fil-PH", speaker: "fil-ph-Neural2-A" },
  },
  {
    code: "th-th",
    shortCode: "th",
    name: "タイ語（タイ）",
    placeholder: "พูดภาษาของคุณ",
    speak: { code: "th-TH", speaker: "th-TH-Neural2-C" },
  },
  {
    code: "id-id",
    shortCode: "id",
    name: "インドネシア語（インドネシア）",
    placeholder: "berbicaralah dalam bahasa Anda",
    speak: { code: "id-ID", speaker: "id-ID-Wavenet-D" },
  },
  {
    code: "ms-my",
    shortCode: "ms",
    name: "マレー語（マレーシア）",
    placeholder: "bercakap bahasa anda",
    speak: { code: "ms-MY", speaker: "ms-MY-Wavenet-D" },
  },
  {
    code: "vi-vn",
    shortCode: "vi",
    name: "ベトナム語（ベトナム）",
    placeholder: "nói ngôn ngữ của bạn",
    speak: { code: "vi-VN", speaker: "vi-VN-Wavenet-A" },
  },
  {
    code: "ko-kr",
    shortCode: "ko",
    name: "韓国語（韓国）",
    placeholder: "언어로 말하기",
    speak: { code: "ko-KR", speaker: "ko-KR-Wavenet-A" },
  },
  {
    code: "fr-fr",
    shortCode: "fr",
    name: "フランス語（フランス）",
    placeholder: "parle ta langue",
    speak: { code: "fr-FR", speaker: "fr-FR-Neural2-C" },
  },
  {
    code: "de-de",
    shortCode: "de",
    name: "ドイツ語（ドイツ）",
    placeholder: "deine Sprache zu sprechen",
    speak: { code: "de-DE", speaker: "de-DE-Wavenet-F" },
  },
  {
    code: "it-it",
    shortCode: "it",
    name: "イタリア語（イタリア）",
    placeholder: "parla la tua lingua",
    speak: { code: "it-IT", speaker: "it-IT-Wavenet-B" },
  },
  {
    code: "hi-in",
    shortCode: "hi",
    name: "ヒンディー語（インド）",
    placeholder: "अपनी भाषा बोलें",
    speak: { code: "hi-IN", speaker: "hi-IN-Wavenet-C" },
  },
  {
    code: "pt-br",
    shortCode: "pt",
    name: "ポルトガル語（ブラジル）",
    placeholder: "fale sua língua",
    speak: { code: "pt-BR", speaker: "pt-BR-Wavenet-B" },
  },
  {
    code: "uk-ua",
    shortCode: "uk",
    name: "ウクライナ語（ウクライナ）",
    placeholder: "говорити своєю мовою",
    speak: { code: "uk-UA", speaker: "uk-UA-Wavenet-A" },
  },
  {
    code: "ru-ru",
    shortCode: "ru",
    name: "ロシア語（ロシア）",
    placeholder: "говори на своем языке",
    speak: { code: "ru-RU", speaker: "ru-RU-Wavenet-A" },
  },
  {
    code: "ar-ae",
    shortCode: "ar",
    name: "アラビア語（アラブ首長国連邦）",
    placeholder: "تحدث لغتك",
    speak: { code: "ar-XA", speaker: "ar-XA-Wavenet-C" },
  },
];
